### ISSUE TITLE
Unable to load PNG images

### ISSUE THREAD

**Issue by sreeni5493** [alankbi/detecto#29]
The dataset loader fails to load PNG images. Any reason why?

**Comment by alankbi** [comment]
The most likely error is that the PNG images have 4 channels instead of 3, i.e. RGBA vs. RGB. You’ll want to convert your images from RGBA to RGB, which you can do by applying a custom transform when creating your Dataset. For example:

```python
from detecto import core, utils
from torchvision import transforms

augmentations = transforms.Compose([
    transforms.Lambda(lambda x: x[:,:,:3]),
    transforms.ToTensor(),
    utils.normalize_transform(),
])

dataset = core.Dataset('images/', transform=augmentations)
```

Here, the `transforms.Lambda(lambda x: x[:,:,:3])` takes in an image and returns only the first three channels (RGB), which should allow you to use your Dataset as normal.

**Comment by sreeni5493** [comment]
Hi,

Issue is solved. Issue was in labelIMG produced xml. The filename did not include .png

Once I added that, it worked. Apologies. Issue is not with Detecto.
